### ISSUE TITLE
什么时候能够出个支持react-native-0.33以上版本的？

### ISSUE THREAD

**Issue by mxlib** [ali322/CNodeRN#10]
现在的版本，升级到0.33就出问题了
![screenshot_20160923-164942](https://cloud.githubusercontent.com/assets/17589907/18779933/c0c564ee-81ad-11e6-9f8b-09c89bd9dae7.png)

**Comment by ali322** [comment]
我会尽快升级

**Comment by ali322** [comment]
@mxlib 已升级至v0.34.2
