### ISSUE TITLE
Could not find property 'MYAPP_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}

### ISSUE THREAD

**Issue by shenhua123** [ali322/CNodeRN#11]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sh/Documents/TempProject/CNodeRN/android/app/build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'MYAPP_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

**Comment by ali322** [comment]
make sure `~/.gradle/gradle.properties` file exist,and should contains following content(your own keystore information)

```bash
 MYAPP_RELEASE_STORE_FILE=rn-apk.keystore
 MYAPP_RELEASE_KEY_ALIAS=rn-apk
 MYAPP_RELEASE_STORE_PASSWORD=12345
 MYAPP_RELEASE_KEY_PASSWORD=12345
```

please follow [offical guild](http://facebook.github.io/react-native/docs/signed-apk-android.html)

**Comment by cg-tester** [comment]
Great! Very helpful. Thanks @ali322
