### ISSUE TITLE
dispatch is not defined

### ISSUE THREAD

**Issue by tonyh2021** [ali322/CNodeRN#12]
启动完成进入首页之后，下拉刷新。出现错误。

![image](https://cloud.githubusercontent.com/assets/5045178/25738028/7453f6e2-31ad-11e7-85b2-3ac061e90a2c.png)
![image](https://cloud.githubusercontent.com/assets/5045178/25738000/4dd9138a-31ad-11e7-86ec-84b5a4f3fdc3.png)

我把代码改成这样就没问题了。我是 RN 和 redux 的新手，请问这是个 bug 么？

![image](https://cloud.githubusercontent.com/assets/5045178/25738065/a2ee8ea4-31ad-11e7-9662-a3728041db4c.png)

**Comment by ali322** [comment]
谢谢反馈
