### ISSUE TITLE
一直在欢迎界面，进不去应用

### ISSUE THREAD

**Issue by murrayee** [ali322/CNodeRN#13]

**Comment by ali322** [comment]
请反馈手机系统和版本,谢谢

**Comment by Josephchen-crypto** [comment]
@ali322 我是iphone6 的 模拟器 也是一直停留在首页进不去。

error: bundling failed: "Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/cdj/Documents/my_project/react-native/CNodeRN/node_modules/react-navigation/src/views/Header.js`: Module does not exist in the module map\n\n

上面是具体的错误。麻烦帮忙看看

**Comment by ali322** [comment]
rm -rf node_modules && npm install

**Comment by dangyanglim** [comment]
![image](https://user-images.githubusercontent.com/16640185/34345151-a4df13ea-ea27-11e7-8ff4-c56ae915b848.png)

**Comment by dangyanglim** [comment]
@ali322 点了esc就卡在欢迎界面了

**Comment by panyy** [comment]
报同样的错误了。
