### ISSUE TITLE
运行的时候报错，请问怎么解决

### ISSUE THREAD

**Issue by hlj2722** [ali322/CNodeRN#17]
android sdk ：2.3.3
win10

运行 react-native run-android的时候报以下错误，

:react-native-code-push:generateReleaseResValues UP-TO-DATE
:react-native-code-push:generateReleaseResources UP-TO-DATE
:react-native-code-push:mergeReleaseResources UP-TO-DATE
:react-native-code-push:processReleaseManifest UP-TO-DATE
:react-native-code-push:processReleaseResources UP-TO-DATE
:react-native-code-push:generateReleaseSources UP-TO-DATE
:react-native-code-push:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-code-push:compileReleaseJavaWithJavac
:react-native-code-push:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\rn\CNodeRN\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePush.java:291: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
注: D:\rn\CNodeRN\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
:react-native-code-push:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.639 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by ali322** [comment]
android sdk 版本太低了吧

**Comment by hlj2722** [comment]
请问android sdk 要求什么版的

**Comment by ali322** [comment]
5.0 以上吧,太低的我没试过

**Comment by hlj2722** [comment]
5.0 指的是android 平台版本吧，我的android api 版本是23 对应的是平台是6.0啊，你的开发环境版本是多少啊

**Comment by ali322** [comment]
请确认 RN 版本是否一致
