### ISSUE TITLE
依赖有冲突

### ISSUE THREAD

**Issue by sumingliang** [ali322/CNodeRN#7]
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/sumingliang/.nvm/versions/node/v4.4.5/bin/node" "/Users/sumingliang/.nvm/versions/node/v4.4.5/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.30.0 wants react@~15.2.0
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-addons-test-utils@15.3.0 wants react@^15.3.0
npm ERR! peerinvalid Peer react-dom@15.3.0 wants react@^15.3.0
npm ERR! peerinvalid Peer react-native-mock@0.2.5 wants react@*
npm ERR! peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0

**Comment by ali322** [comment]
u should install react package in version 15.2.0

`npm install react@15.2.0`
