### ISSUE TITLE
SyntaxError  @preferredThemer(defaultStyles)

### ISSUE THREAD

**Issue by sumingliang** [ali322/CNodeRN#8]
at File.parseCode (/Users//react-native/CNodeRN/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:603:20)
[23:28:27] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false
[23:28:27] <START> find dependencies
transformed 830/844 (98%)[node-haste] Encountered an error while persisting cache:

> SyntaxError: /Users//react-native/CNodeRN/js/campus/updater.js: Unexpected token (53:0)
>   51 | const defaultStyles = StyleSheet.create(Object.assign({},stylesForAll))
>   52 | 
> 
> > 53 | @preferredThemer(defaultStyles)
> >      | ^
> >   54 | class Updater extends Component{
> >   55 |     constructor(props){
> >   56 |         super(props)
> >     at Parser.pp.raise (/Users/react-native/CNodeRN/node_modules/react-native/node_modules/babylon/lib/parser/location.js:22:13)
> >     at Parser.pp.unexpected (/Users//react-native/CNodeRN/node_modules/react-native/node_modules/babylon/lib/parser/util.js:89:8)

**Comment by ali322** [comment]
1. install babel plugin `nam install babel-plugin-transform-decorators-legacy babel-preset-react-native --save-dev`
2. place your own .babelrc file in project root directory like this

```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```
